apiVersion: v1
kind: ConfigMap
metadata:
  name: gatewaybridge-configmap
  namespace: lora
  labels:
    app: gatewaybridge
data:
  lora-gateway-bridge.toml: |-
    [backend.mqtt]
    server="tcp://mosquitto:1883"
    username="{{ .Values.mosquitto.user }}"
    password="{{ .Values.mosquitto.password }}"
