apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatewaybridge
  name: gatewaybridge
  namespace: lora
spec:
  ports:
  - name: "1700"
    port: 1700
    protocol: UDP
    targetPort: 1700
  selector:
    app: gatewaybridge
status:
  loadBalancer: {}
