apiVersion: v1
kind: Service
metadata:
  labels:
    app: loraappserver
  name: loraappserver
  namespace: lora
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8001"
    port: 8001
    targetPort: 8001
  - name: "8003"
    port: 8003
    targetPort: 8003
  selector:
    app: loraappserver
status:
  loadBalancer: {}
