dependencies:
- name: gatewaybridge
  version: 1.0.0
  repository: file://./charts/gatewaybridge
  condition: gatewaybridge.enabled
- name: loraappserver
  version: 1.0.0
  repository: file://./charts/loraappserver
  condition: loraappserver.enabled
- name: loraserver
  version: 1.0.0
  repository: file://./charts/loraserver
  condition: loraserver.enabled
- name: mosquitto
  version: 1.0.0
  repository: file://./charts/mosquitto
  condition: mosquitto.enabled
- name: postgres
  version: 1.0.0
  repository: file://./charts/postgres
  condition: postgres.enabled
- name: redis
  version: 1.0.0
  repository: file://./charts/redis
  condition: redis.enabled
