apiVersion: v1
kind: Service
metadata:
  labels:
    app: loraserver
  name: loraserver
  namespace: lora
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: loraserver
status:
  loadBalancer: {}
