apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: lora
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/db-files/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-configmap
  namespace: lora
  labels:
    app: postgres
data:
{{ (.Files.Glob "initdb/001-init-loraserver_ns.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "initdb/002-init-loraserver_as.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "initdb/003-loraserver_as_trgm.sh").AsConfig | indent 2 }}
