apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: lora
  labels:
    app: mosquitto
spec:
  ports:
  - name: mqtt
    port: 1883
  - name: websocket
    port: 9001
  selector:
    app: mosquitto