version: "3"

services:
  loraserver:
    image: loraserver/loraserver:2.3.0
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - /data/lora/lora-server:/etc/loraserver

  loraappserver:
    image: loraserver/lora-app-server:2.4.0
    depends_on:
      - postgresql
      - redis
    ports:
      - 8080:8080
      - 8001:8001
      - 8003:8003
    volumes:
      - /data/lora/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:2.6.1
    depends_on:
      - mosquitto
    ports:
      - 1700:1700/udp
    volumes:
      - /data/lora/lora-gateway-bridge:/etc/lora-gateway-bridge
  
  lorageoserver:
    image: loraserver/lora-geo-server:2.0.1
    ports:
      - 8005:8005
    volumes:
      - /data/lora/lora-geo-server:/etc/lora-geo-server
  
  postgresql:
    image: postgres:11.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data/lora/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:5.0.0-alpine3.8
    ports:
      - 6379:6379

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /data/lora/mosquitto:/mosquitto
