# See https://www.loraserver.io/lora-gateway-bridge/install/config/ for a full
# configuration example and documentation.

[backend.mqtt]
server="tcp://mosquitto:1883"
username=""
password=""

uplink_topic_template="gateway/{{ .MAC }}/rx"
downlink_topic_template="gateway/{{ .MAC }}/tx"
stats_topic_template="gateway/{{ .MAC }}/stats"
ack_topic_template="gateway/{{ .MAC }}/ack"
config_topic_template="gateway/{{ .MAC }}/config"

marshaler="v2_json"
